name 'sample-go-cm'
maintainer 'Julien Berard'
maintainer_email 'jujugrrr@gmail.com'
license 'apache2'
description 'Installs/Configures the sample-go application'
long_description 'Installs/Configures the sample-go application'
issues_url 'https://github.com/jujugrrr/sample-go-cm/issues'
source_url 'https://github.com/jujugrrr/sample-go-cm/'
version '0.1.1'

depends 'apt'
depends 'golang'
depends 'nginx', '~> 2.7.6'
depends 'supervisor'
depends 'sudo'
depends 'user'
